Add files via upload
SistemaFinanceiroNacional/login-senha-ryan pull request #7
Opened 2022-03-30 22:42 UTC by ryanjorgeac

2022-04-05 15:31 UTC, petrolifero commented on cursor.py
> +                register = {"login":logindoc,"password":passworddoc, "saldo":saldo}
why select know the column's names if is open to use any table, ```        with open(f"{fromTable}.txt") as archive:``` ???

2022-04-09 03:22 UTC, petrolifero commented on test_contas.py
>  def test_authentication_on_second_account_with_real_archive():
this test fails

2022-04-11 16:27 UTC, petrolifero requested changes

2022-04-11 16:27 UTC, petrolifero commented on cursor.py
>      def insert(self,values,into):
insert is supposed to be general, but he knows the collumns name?

2022-04-11 22:00 UTC, ryanjorgeac commented on condition.py
> +class columnname(projection):
Done.

2022-06-01 15:16 UTC, petrolifero submitted a review, later dismissed

2022-06-03 21:53 UTC, petrolifero approved these changes

2022-06-03 21:53 UTC, merged